# Generated by Django 4.1.3 on 2022-11-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect4game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
